### ISSUE TITLE
updateConf.py to change symlinks for chConfig from trim runs

### ISSUE THREAD

**Issue by giovanni-mocellin** [cms-gem-daq-project/sw_utils#43]
## Brief summary of issue

At the moment, it is possible to change the symlinks for  chConfig and vfatConfig if an scurve or an sbitThreshold scan is taken.
If a trim run is taken, it is presently not possible to get a symlink for the chConfig.txt derived from the trimmed scurve taken at the end of the procedure. So it would be nice to have the tool updateConf.py with an option for trim runs.

### Types of issue

- [ ] Bug report (report an issue with the code)
- [x] Feature request (request for change which adds functionality)

## Expected Behavior

updateConf.py with an option in order to be able to change the symlinks for chConfig.txt in the folder $DATA_PATH/configs for trim runs. Perhaps, a '-t' option...

## Current Behavior

updateConf.py has -c (chConfig = from scurve) and -v (vfatConfig = from sbitThresh) options only.

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

QC8 DAQ machine.
* Version used:
* Shell used:

**Comment by lpetre-ulb** [comment]
Feature added in #46.
